import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it } from 'vitest'
import { App } from './App'
import { STORAGE_KEY } from './domain/persistence'

const metric = (label: string) => screen.getByText(label).closest('div[class*=card], section, article')?.textContent ?? ''
const row = (text: RegExp) => screen.getByRole('button', { name: text })
// The open row's detail cell (one is open at a time).
const detail = () => {
  const cell = document.querySelector<HTMLElement>('td[id^="case-"]')
  if (!cell) throw new Error('No expanded row')
  return cell
}

beforeEach(() => {
  localStorage.clear()
})

describe('Reconciliation prototype', () => {
  it('starts with 24 records in 16 cases, the auto-matched pairs in the main table', async () => {
    render(<App />)
    expect(screen.getByRole('heading', { name: 'Transactions' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'All (24)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Auto-matched (10)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Suggested (6)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (14)' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Already matched/ })).not.toBeInTheDocument()
    expect(screen.getByText(/Showing 16 of 16 review cases · 12 bank transactions \/ 12 ledger entries/)).toBeInTheDocument()
    await userEvent.setup().click(screen.getByRole('tab', { name: 'Auto-matched (10)' }))
    expect(screen.getByText('5 auto-matched pairs · 10 records awaiting review')).toBeInTheDocument()
    expect(within(row(/Nov 03 · Stripe payout/).closest('tr')!).getByText('Auto-matched')).toBeInTheDocument()
    expect(metric('Remaining difference')).toContain('$320.00')
    expect(metric('Cleared balance')).toContain('$100,000.00')
  })

  it('confirms a suggestion from the keyboard and offers Undo in the expanded row', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(screen.queryByRole('columnheader', { name: 'Action' })).not.toBeInTheDocument()
    row(/Nov 04 · ACH NORTH/).focus()
    await user.keyboard('{Enter}')
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (2)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (12)' })).toBeInTheDocument()
    expect(metric('Book balance')).toContain('$109,970.00')
    expect(metric('Cleared balance')).toContain('$97,600.00')
    // A later action elsewhere doesn't take away this row's Undo.
    await user.click(row(/Nov 12 · DELTA PAY/))
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (4)' })).toBeInTheDocument()
    await user.click(row(/Nov 04 · ACH NORTH/))
    expect(within(detail()).getByText('Match confirmed')).toBeInTheDocument()
    await user.click(within(detail()).getByRole('button', { name: 'Undo' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (2)' })).toBeInTheDocument()
    expect(metric('Cleared balance')).toContain('$103,200.00')
    // Undo collapses the row and keeps focus on it.
    expect(row(/Nov 04 · ACH NORTH/)).toHaveAttribute('aria-expanded', 'false')
    expect(row(/Nov 04 · ACH NORTH/)).toHaveFocus()
  })

  it('dismisses a suggestion without changing balances and restores it from the notice', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Nov 18 · ALDER SUPPLY/))
    await user.click(within(detail()).getByRole('button', { name: 'Dismiss suggestion' }))
    expect(screen.getByRole('tab', { name: 'Suggested (4)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (14)' })).toBeInTheDocument()
    expect(screen.getByText('Suggestion dismissed')).toBeInTheDocument()
    expect(metric('Remaining difference')).toContain('$320.00')
    await user.click(screen.getByRole('button', { name: /Undo dismissing GL-1108/ }))
    expect(screen.getByRole('tab', { name: 'Suggested (6)' })).toBeInTheDocument()
  })

  it('searches with the keyboard, then confirms the selected entry', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Nov 18 · ALDER SUPPLY/))
    await user.click(within(detail()).getByRole('button', { name: 'Dismiss suggestion' }))
    const combo = within(detail()).getByRole('combobox')
    await user.click(combo)
    await user.type(combo, 'ald-17')
    expect(within(detail()).getAllByRole('option')).toHaveLength(1)
    await user.keyboard('{ArrowDown}{Enter}')
    expect(screen.getByText('Selected ledger entry')).toBeInTheDocument()
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (2)' })).toBeInTheDocument()
    expect(row(/Nov 18 · ALDER SUPPLY/)).toHaveFocus()
  })

  it('finds entries by date in the single search field', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Nov 18 · ALDER SUPPLY/))
    await user.click(within(detail()).getByRole('button', { name: 'Dismiss suggestion' }))
    expect(within(detail()).queryByText(/Required for a match/)).not.toBeInTheDocument()
    expect(within(detail()).queryByRole('button', { name: /Add a date filter/ })).not.toBeInTheDocument()
    const combo = within(detail()).getByPlaceholderText('Search by keywords, date or amount')
    await user.click(combo)
    // Every unmatched ledger entry is listed, the two with the same amount first.
    const all = within(detail()).getAllByRole('option').map((o) => o.textContent)
    expect(all).toHaveLength(12)
    expect(all.slice(0, 2)).toEqual([expect.stringContaining('GL-1108'), expect.stringContaining('GL-1107')])
    await user.type(combo, '12,500')
    expect(within(detail()).getAllByRole('option').map((o) => o.textContent)).toEqual([expect.stringContaining('GL-1100')])
    await user.clear(combo)
    await user.type(combo, 'Nov 19')
    expect(within(detail()).getAllByRole('option').map((o) => o.textContent)).toEqual([expect.stringContaining('GL-1108')])
    await user.clear(combo)
    await user.type(combo, '11/17')
    expect(within(detail()).getAllByRole('option').map((o) => o.textContent)).toEqual([expect.stringContaining('GL-1107')])
  })

  it('refuses to confirm a searched entry with a different amount', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Nov 18 · ALDER SUPPLY/))
    await user.click(within(detail()).getByRole('button', { name: 'Dismiss suggestion' }))
    const combo = within(detail()).getByRole('combobox')
    await user.click(combo)
    await user.type(combo, '12,500')
    await user.keyboard('{ArrowDown}{Enter}')
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(within(detail()).getAllByText(/amounts differ/).length).toBeGreaterThan(0)
    expect(screen.getByRole('tab', { name: 'Confirmed (0)' })).toBeInTheDocument()
  })

  it('shows outstanding errors on the fields without a "Nothing was changed" banner', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Check 1042/))
    const open = within(detail()).getAllByRole('button', { name: 'Document as outstanding' })
    if (open.length > 1) await user.click(open[0])
    const submit = within(detail()).getAllByRole('button', { name: 'Document as outstanding' })
    await user.click(submit[submit.length - 1])
    expect(within(detail()).queryByText('Nothing was changed')).not.toBeInTheDocument()
    expect(within(detail()).getByText('Not on the November statement')).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Outstanding (0)' })).toBeInTheDocument()
  })

  it('keeps expense input after a rejected submit and creates the entry once', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Monthly bank service fee/))
    await user.click(within(detail()).getByRole('button', { name: 'Create entry…' }))
    const date = within(detail()).getByLabelText('Posting date')
    await user.clear(date)
    await user.type(date, 'Dec 1, 2025')
    await user.click(within(detail()).getByRole('button', { name: 'Create and match' }))
    expect(within(detail()).getByText('The posting date must be in November 2025.')).toBeInTheDocument()
    expect(within(detail()).getByText('Choose the expense category that records this cost.')).toBeInTheDocument()
    expect(date).toHaveValue('Dec 1, 2025')
    await user.clear(date)
    await user.type(date, 'Nov 30, 2025')
    await user.click(within(detail()).getByRole('button', { name: /Expense category/ }))
    await user.click(screen.getByRole('option', { name: 'Bank Fees' }))
    await user.dblClick(within(detail()).getByRole('button', { name: 'Create and match' }))
    expect(screen.getAllByText(/GL-1115/).length).toBeGreaterThan(0)
    expect(metric('Book balance')).toContain('$109,955.00')
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)!)
    expect(saved.state?.generated ?? saved.generated).toHaveLength(1)
  })

  it('expands and collapses a case when any part of its row is clicked', async () => {
    const user = userEvent.setup()
    render(<App />)
    const button = row(/Nov 04 · ACH NORTH/)
    await user.click(within(button.closest('tr')!).getByText('GL-1101 · Nov 03'))
    expect(button).toHaveAttribute('aria-expanded', 'true')
    // The status pill shows its tooltip instead of toggling the row.
    await user.click(within(button.closest('tr')!).getByText('Suggested'))
    expect(button).toHaveAttribute('aria-expanded', 'true')
    await user.click(within(button.closest('tr')!).getAllByText(/2,400\.00/, { selector: 'td' })[0])
    expect(button).toHaveAttribute('aria-expanded', 'false')
    expect(button).toHaveFocus()
  })

  it('explains each status pill in a tooltip on hover and keyboard focus without expanding the row', async () => {
    const user = userEvent.setup()
    render(<App />)
    const tr = row(/Nov 04 · ACH NORTH/).closest('tr')!
    const pill = within(tr).getByText('Suggested').closest<HTMLElement>('[data-tooltip-trigger]')!
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    await user.hover(pill)
    expect(screen.getByRole('tooltip')).toHaveTextContent('A possible match is ready for your review.')
    expect(pill).toHaveAccessibleDescription('A possible match is ready for your review.')
    await user.click(pill)
    expect(row(/Nov 04 · ACH NORTH/)).toHaveAttribute('aria-expanded', 'false')
    await user.unhover(pill)
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    // From the keyboard: Tab from the row's disclosure reaches the pill; Escape hides the tooltip.
    row(/Nov 03 · Stripe payout/).focus()
    await user.tab()
    expect(screen.getByRole('tooltip')).toHaveTextContent('The system found a match. Review the details to confirm it.')
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    expect(row(/Nov 03 · Stripe payout/)).toHaveAttribute('aria-expanded', 'false')
    await user.hover(within(row(/Outgoing wire fee/).closest('tr')!).getByText('Unmatched'))
    expect(screen.getByRole('tooltip')).toHaveTextContent('This transaction still needs a match or an explanation.')
  })

  it('resets the demo to the original data and clears saved actions', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Nov 04 · ACH NORTH/))
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (2)' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reset demo' }))
    await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Reset demo' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (0)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (14)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Auto-matched (10)' })).toBeInTheDocument()
    expect(metric('Cleared balance')).toContain('$100,000.00')
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? 'null')
    const state = saved?.state ?? saved
    expect(state?.matches ?? []).toHaveLength(0)
  })

  it('leaves a case unresolved by collapsing it, with nothing else changed', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(row(/Outgoing wire fee/))
    await user.click(within(detail()).getByRole('button', { name: 'Leave Unresolved' }))
    expect(row(/Outgoing wire fee/)).toHaveAttribute('aria-expanded', 'false')
    expect(row(/Outgoing wire fee/)).toHaveFocus()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(within(row(/Outgoing wire fee/).closest('tr')!).getByText('Unmatched')).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (14)' })).toBeInTheDocument()
    expect(JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '{"history":[]}').history).toHaveLength(0)
    expect(metric('Remaining difference')).toContain('$320.00')
    await user.click(row(/Outgoing wire fee/))
    expect(row(/Outgoing wire fee/)).toHaveAttribute('aria-expanded', 'true')
  })

  it('reviews an auto-matched pair with the suggested-match actions and Undo', async () => {
    const user = userEvent.setup()
    render(<App />)
    const stripe = () => row(/Nov 03 · Stripe payout/)
    await user.click(stripe())
    expect(within(detail()).getByText('Automatically matched · Awaiting your review')).toBeInTheDocument()
    // Leave Unresolved: collapses, keeps Auto-matched and focus, changes nothing else.
    await user.click(within(detail()).getByRole('button', { name: 'Leave Unresolved' }))
    expect(stripe()).toHaveAttribute('aria-expanded', 'false')
    expect(stripe()).toHaveFocus()
    expect(within(stripe().closest('tr')!).getByText('Auto-matched')).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Auto-matched (10)' })).toBeInTheDocument()
    // Dismiss suggestion: both records become Unmatched, and the notice's Undo restores the pairing.
    await user.click(stripe())
    await user.click(within(detail()).getByRole('button', { name: 'Dismiss suggestion' }))
    expect(screen.getByRole('tab', { name: 'Auto-matched (8)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Unmatched (16)' })).toBeInTheDocument()
    expect(within(detail()).getByText('Auto-match dismissed')).toBeInTheDocument()
    await user.click(within(detail()).getByRole('button', { name: /Undo dismissing GL-1100/ }))
    expect(screen.getByRole('tab', { name: 'Auto-matched (10)' })).toBeInTheDocument()
    // Confirm match: both records are Confirmed, cleared moves, progress updates; Undo reverses it.
    await user.click(within(detail()).getByRole('button', { name: 'Confirm match' }))
    expect(screen.getByRole('tab', { name: 'Confirmed (2)' })).toBeInTheDocument()
    expect(screen.getByRole('tab', { name: 'Auto-matched (8)' })).toBeInTheDocument()
    expect(within(stripe().closest('tr')!).getByText('Confirmed')).toBeInTheDocument()
    expect(metric('Cleared balance')).toContain('$112,500.00')
    expect(screen.getByText(/Progress: 2 of 24 records reviewed/)).toBeInTheDocument()
    await user.click(stripe())
    await user.click(within(detail()).getByRole('button', { name: 'Undo' }))
    expect(screen.getByRole('tab', { name: 'Auto-matched (10)' })).toBeInTheDocument()
    expect(metric('Cleared balance')).toContain('$100,000.00')
  })

  it('opens the navigation menu on narrow screens and closes it with Escape', async () => {
    const user = userEvent.setup()
    render(<App />)
    const menu = screen.getByRole('button', { name: 'Menu' })
    expect(menu).toHaveAttribute('aria-expanded', 'false')
    await user.click(menu)
    expect(menu).toHaveAttribute('aria-expanded', 'true')
    expect(document.getElementById('app-sidebar')).toContainElement(document.activeElement as HTMLElement)
    await user.keyboard('{Escape}')
    expect(menu).toHaveAttribute('aria-expanded', 'false')
    expect(menu).toHaveFocus()
  })

  it('blocks completion and lists the reasons', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /Complete reconciliation/ }))
    const alert = screen.getByRole('alert')
    expect(alert).toHaveTextContent('10 of 24 records are auto-matched and still need your review')
    expect(alert).toHaveTextContent('14 of 24 records are still unmatched (6 of them have a suggested match)')
    expect(alert).toHaveTextContent('The remaining difference is $320.00')
  })

  it('shows a recovery screen for unreadable saved data instead of discarding it', () => {
    localStorage.setItem(STORAGE_KEY, '{')
    render(<App />)
    expect(screen.getByRole('button', { name: /Try again/ })).toBeInTheDocument()
    expect(localStorage.getItem(STORAGE_KEY)).toBe('{')
  })
})
